Restore the  check
Signed-off-by: Mario Loriedo <mario.loriedo@gmail.com>

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -134,6 +134,8 @@ release_task:
     dnf install 'dnf-command(config-manager)'
     dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
     dnf install -y gh git
+    # Get latest buildah and podman otherwise the
+    # creation and the upload of the OCI artifact fails
     dnf upgrade -y --releasever=40 podman buildah
   release_script: |
     set +o verbose
@@ -148,8 +150,6 @@ release_task:
         echo "Upload for $arch not provided (was skipped in build), will reuse last release"
         FETCH1="$HTTP_PREFIX/$VER_PFX-rootfs-$arch.tar.zst"
         FETCH2="$HTTP_PREFIX/$VER_PFX-latest-$arch"
-        $PCURL_RETRY -LO "$FETCH1"
-        $PCURL_RETRY -LO "$FETCH2"
         echo -e "none\n" >> ./changes
       else
         SHOULD_RELEASE=1
@@ -158,15 +158,13 @@ release_task:
       fi
     done
 
-    # Temporarly disable this check to force a release
-    # even if there are no changes
-    # if [ -z "$SHOULD_RELEASE" ]; then 
-    #   echo "All builds were skipped, Nothing to release."
-    #   exit
-    # fi
-    # test -z "$FETCH1" || echo "Fetching past artifacts for skipped builds "
-    # test -z "$FETCH1" || $PCURL_RETRY -LO "$FETCH1"
-    # test -z "$FETCH2" || $PCURL_RETRY -LO "$FETCH2"
+    if [ -z "$SHOULD_RELEASE" ]; then 
+      echo "All builds were skipped, Nothing to release."
+      exit
+    fi
+    test -z "$FETCH1" || echo "Fetching past artifacts for skipped builds "
+    test -z "$FETCH1" || $PCURL_RETRY -LO "$FETCH1"
+    test -z "$FETCH2" || $PCURL_RETRY -LO "$FETCH2"
 
     # temporary 5.1, 5.2 and 5.3 clone until divergance occurs
     for arch in amd64 arm64; do
