Switch to fedora 40 and force release
Signed-off-by: Mario Loriedo <mario.loriedo@gmail.com>

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -2,7 +2,7 @@ env:
   IMAGE_TAG: 40 
   GITHUB_SERVER_URL: "https://github.com"
   CIRRUS_SHELL: bash
-  IMAGE_SUFFIX: "c20240227t125812z-f39f38d13"
+  IMAGE_SUFFIX: "c20240821t171500z-f40f39d13"
   FEDORA_AARCH64_AMI: "fedora-podman-aws-arm64-${IMAGE_SUFFIX}"
   FEDORA_AMI: "fedora-aws-${IMAGE_SUFFIX}"
   PCURL_RETRY: "curl --retry 5 --retry-delay 8 --retry-all-errors -L"
@@ -136,7 +136,7 @@ release_task:
     dnf install -y gh git
     # Get latest buildah and podman otherwise the
     # creation and the upload of the OCI artifact fails
-    dnf upgrade -y --releasever=40 podman buildah
+    # dnf upgrade -y --releasever=40 podman buildah
   release_script: |
     set +o verbose
     HTTP_PREFIX="$GITHUB_SERVER_URL/$CIRRUS_REPO_FULL_NAME/releases/latest/download"
@@ -150,6 +150,9 @@ release_task:
         echo "Upload for $arch not provided (was skipped in build), will reuse last release"
         FETCH1="$HTTP_PREFIX/$VER_PFX-rootfs-$arch.tar.zst"
         FETCH2="$HTTP_PREFIX/$VER_PFX-latest-$arch"
+        # Temporarly download last release artifacts to force release
+        $PCURL_RETRY -LO "$FETCH1"
+        $PCURL_RETRY -LO "$FETCH2"
         echo -e "none\n" >> ./changes
       else
         SHOULD_RELEASE=1
@@ -158,13 +161,14 @@ release_task:
       fi
     done
 
-    if [ -z "$SHOULD_RELEASE" ]; then 
-      echo "All builds were skipped, Nothing to release."
-      exit
-    fi
-    test -z "$FETCH1" || echo "Fetching past artifacts for skipped builds "
-    test -z "$FETCH1" || $PCURL_RETRY -LO "$FETCH1"
-    test -z "$FETCH2" || $PCURL_RETRY -LO "$FETCH2"
+    # Temporarly disable this check to force release
+    # if [ -z "$SHOULD_RELEASE" ]; then 
+    #   echo "All builds were skipped, Nothing to release."
+    #   exit
+    # fi
+    # test -z "$FETCH1" || echo "Fetching past artifacts for skipped builds "
+    # test -z "$FETCH1" || $PCURL_RETRY -LO "$FETCH1"
+    # test -z "$FETCH2" || $PCURL_RETRY -LO "$FETCH2"
 
     # temporary 5.1, 5.2 and 5.3 clone until divergance occurs
     for arch in amd64 arm64; do
